### PR TITLE
Ticked version, regenerated if needed. (Double-check reqs!)

### PR DESCRIPTION
**Pull request by pmlandwehr**
Made using `tick_my_feedstocks.py`!
- [x] **I have vetted this recipe**

### CODE REVIEW

**Comment by jakirkham** [comment]
Can you please hold up on merging for a little bit? Trying to fix an issue in the upload step. Thanks.

**Comment by jakirkham** [comment]
Ok, should be good now.

**Comment by pmlandwehr** [comment]
@conda-forge-admin please rerender

**Comment by pmlandwehr** [comment]
Merged a bad Appveyor build, but only CircleCI Matters since it's noarch: python

**Comment by jakirkham** [comment]
Recommend raising an issue with the AppVeyor folks about this building anyways despite having `appveyor.yml` removed.

**Pull request merged**
